networks:
  supabase-network:
    driver: bridge
services:
  analytics:
    container_name: supabase-analytics
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_DATABASE: ${POSTGRES_DB:-postgres}
      DB_HOSTNAME: ${POSTGRES_HOST:-db}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_PORT: ${POSTGRES_PORT:-5432}
      DB_SCHEMA: _analytics
      DB_USERNAME: supabase_admin
      LOGFLARE_API_KEY: ${LOGFLARE_API_KEY:-your-super-secret-and-long-logflare-key}
      LOGFLARE_FEATURE_FLAG_OVERRIDE: multibackend=true
      LOGFLARE_MIN_CLUSTER_SIZE: 1
      LOGFLARE_NODE_HOST: 127.0.0.1
      LOGFLARE_SINGLE_TENANT: true
      LOGFLARE_SUPABASE_MODE: true
      POSTGRES_BACKEND_SCHEMA: _analytics
      POSTGRES_BACKEND_URL: postgresql://supabase_admin:${POSTGRES_PASSWORD}@${POSTGRES_HOST:-db}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-postgres}
    image: supabase/logflare:1.4.0
    networks:
    - supabase-network
  auth:
    container_name: supabase-auth
    depends_on:
      db:
        condition: service_healthy
    environment:
      API_EXTERNAL_URL: ${API_EXTERNAL_URL}
      GODEBUG: tlskyber=0
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      GOTRUE_DB_DATABASE_URL: postgres://supabase_auth_admin:${POSTGRES_PASSWORD}@${POSTGRES_HOST:-db}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-postgres}
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DISABLE_SIGNUP: ${DISABLE_SIGNUP:-false}
      GOTRUE_EXTERNAL_ANONYMOUS_USERS_ENABLED: ${ENABLE_ANONYMOUS_USERS:-false}
      GOTRUE_EXTERNAL_EMAIL_ENABLED: ${ENABLE_EMAIL_SIGNUP:-true}
      GOTRUE_EXTERNAL_PHONE_ENABLED: ${ENABLE_PHONE_SIGNUP:-false}
      GOTRUE_JWT_ADMIN_ROLES: service_role
      GOTRUE_JWT_AUD: authenticated
      GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
      GOTRUE_JWT_EXP: ${JWT_EXPIRY:-3600}
      GOTRUE_JWT_SECRET: ${JWT_SECRET}
      GOTRUE_LOG_LEVEL: debug
      GOTRUE_MAILER_AUTOCONFIRM: ${ENABLE_EMAIL_AUTOCONFIRM:-false}
      GOTRUE_MAILER_LOCAL_NAME: sm31.hosting.reg.ru
      GOTRUE_MAILER_URLPATHS_CONFIRMATION: ${MAILER_URLPATHS_CONFIRMATION:-/auth/v1/verify}
      GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE: ${MAILER_URLPATHS_EMAIL_CHANGE:-/auth/v1/verify}
      GOTRUE_MAILER_URLPATHS_INVITE: ${MAILER_URLPATHS_INVITE:-/auth/v1/verify}
      GOTRUE_MAILER_URLPATHS_RECOVERY: ${MAILER_URLPATHS_RECOVERY:-/auth/v1/verify}
      GOTRUE_RATE_LIMIT_EMAIL_SENT: 100
      GOTRUE_RATE_LIMIT_HEADER: X-Forwarded-For
      GOTRUE_SITE_URL: ${SITE_URL}
      GOTRUE_SMS_AUTOCONFIRM: ${ENABLE_PHONE_AUTOCONFIRM:-false}
      GOTRUE_SMTP_ADMIN_EMAIL: ${SMTP_ADMIN_EMAIL:-}
      GOTRUE_SMTP_HOST: ${SMTP_HOST:-}
      GOTRUE_SMTP_LOCAL_NAME: sm31.hosting.reg.ru
      GOTRUE_SMTP_MAX_FREQUENCY: 1ns
      GOTRUE_SMTP_PASS: ${SMTP_PASS:-}
      GOTRUE_SMTP_PORT: ${SMTP_PORT:-587}
      GOTRUE_SMTP_SENDER_NAME: ANDO JV
      GOTRUE_SMTP_USER: ${SMTP_USER:-}
      GOTRUE_HOOK_SEND_EMAIL_ENABLED: "true"
      GOTRUE_HOOK_SEND_EMAIL_TIMEOUT: "30s"
      GOTRUE_HOOK_SEND_EMAIL_URI: "http://127.0.0.1:5000/hook/send-email"
      GOTRUE_URI_ALLOW_LIST: ${ADDITIONAL_REDIRECT_URLS:-}
      LOG_LEVEL: debug
    image: supabase/gotrue:v2.186.0
    networks:
    - supabase-network
  db:
    command:
    - postgres
    - -c
    - config_file=/etc/postgresql/postgresql.conf
    - -c
    - log_min_messages=fatal
    container_name: supabase-db
    environment:
      JWT_EXP: ${JWT_EXPIRY:-3600}
      JWT_SECRET: ${JWT_SECRET}
      PGDATABASE: ${POSTGRES_DB:-postgres}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGPORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_HOST: /var/run/postgresql
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    expose:
    - '5432'
    healthcheck:
      interval: 5s
      retries: 10
      test: pg_isready -U postgres -h localhost
      timeout: 5s
    image: supabase/postgres:15.1.1.61
    networks:
    - supabase-network
    volumes:
    - ${DB_DATA_PATH}:/var/lib/postgresql/data:Z
    - ./docker/volumes/db/webhooks.sql:/docker-entrypoint-initdb.d/init-scripts/98-webhooks.sql:Z
    - ./docker/volumes/db/roles.sql:/docker-entrypoint-initdb.d/init-scripts/99-roles.sql:Z
    - ./docker/volumes/db/jwt.sql:/docker-entrypoint-initdb.d/init-scripts/99-jwt.sql:Z
    - ./docker/volumes/db/realtime.sql:/docker-entrypoint-initdb.d/migrations/99-realtime.sql:Z
    - ./docker/volumes/db/init/00-migrations.sql:/docker-entrypoint-initdb.d/migrations/00-migrations.sql:Z
    - ./docker/volumes/db/init/01-seed-admin.sql:/docker-entrypoint-initdb.d/migrations/01-seed-admin.sql:Z
  frontend:
    build:
      args:
        VITE_SUPABASE_PROJECT_ID: ${VITE_SUPABASE_PROJECT_ID}
        VITE_SUPABASE_PUBLISHABLE_KEY: ${ANON_KEY}
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
      context: .
      dockerfile: Dockerfile
      target: ${FRONTEND_BUILD_TARGET:-production}
    container_name: ando-frontend
    depends_on:
      kong:
        condition: service_healthy
    networks:
    - supabase-network
  functions:
    command:
    - start
    - --main-service
    - /home/deno/functions/main
    container_name: supabase-edge-functions
    depends_on:
      db:
        condition: service_healthy
    environment:
      JWT_SECRET: ${JWT_SECRET}
      SUPABASE_ANON_KEY: ${ANON_KEY}
      SUPABASE_DB_URL: postgresql://postgres:${POSTGRES_PASSWORD}@${POSTGRES_HOST:-db}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-postgres}
      SUPABASE_SERVICE_ROLE_KEY: ${SERVICE_ROLE_KEY}
      SUPABASE_URL: http://kong:8000
      VERIFY_JWT: 'true'
    image: supabase/edge-runtime:v1.36.1
    networks:
    - supabase-network
    volumes:
    - ./docker/volumes/functions:/home/deno/functions:Z
  imgproxy:
    container_name: supabase-imgproxy
    environment:
      IMGPROXY_BIND: :8080
      IMGPROXY_ENABLE_WEBP_DETECTION: 'true'
      IMGPROXY_LOCAL_FILESYSTEM_ROOT: /
      IMGPROXY_USE_ETAG: 'true'
    image: darthsim/imgproxy:v3.21
    networks:
    - supabase-network
    volumes:
    - ${STORAGE_DATA_PATH}:/var/lib/storage:ro
  kong:
    container_name: supabase-kong
    depends_on:
      auth:
        condition: service_started
      db:
        condition: service_healthy
      meta:
        condition: service_started
      realtime:
        condition: service_started
      rest:
        condition: service_started
      storage:
        condition: service_started
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: /var/lib/kong/kong.yml
      KONG_DNS_ORDER: LAST,A,CNAME
      KONG_LOG_LEVEL: ${KONG_LOG_LEVEL:-info}
      KONG_NGINX_PROXY_PROXY_BUFFERS: 64 160k
      KONG_NGINX_PROXY_PROXY_BUFFER_SIZE: 160k
      KONG_PLUGINS: request-transformer,cors,key-auth,acl,basic-auth
    expose:
    - '8443'
    healthcheck:
      interval: 10s
      retries: 10
      test:
      - CMD
      - kong
      - health
      timeout: 10s
    image: kong:2.8.1
    networks:
    - supabase-network
    ports:
    - 8000:8000
    volumes:
    - ./docker/kong/kong.yml:/var/lib/kong/kong.yml:ro
  meta:
    container_name: supabase-meta
    depends_on:
      db:
        condition: service_healthy
    environment:
      PG_META_DB_HOST: ${POSTGRES_HOST:-db}
      PG_META_DB_NAME: ${POSTGRES_DB:-postgres}
      PG_META_DB_PASSWORD: ${POSTGRES_PASSWORD}
      PG_META_DB_PORT: ${POSTGRES_PORT:-5432}
      PG_META_DB_USER: supabase_admin
      PG_META_PORT: 8080
    image: supabase/postgres-meta:v0.80.0
    networks:
    - supabase-network
  nginx:
    container_name: ando-nginx
    depends_on:
    - frontend
    - kong
    - studio
    image: nginx:alpine
    networks:
    - supabase-network
    ports:
    - 5173:80
    - 8001:8080
    volumes:
    - ${NGINX_CONFIG_PATH:-./docker/nginx/proxy.conf}:/etc/nginx/conf.d/default.conf:ro
    - ${NGINX_HTPASSWD_PATH:-./docker/nginx/.htpasswd}:/etc/nginx/.htpasswd:ro
  realtime:
    command: 'sh -c "/app/bin/migrate && /app/bin/realtime eval ''Realtime.Release.seeds(Realtime.Repo)''
      && /app/bin/server"

      '
    container_name: supabase-realtime
    depends_on:
      db:
        condition: service_healthy
    environment:
      API_JWT_SECRET: ${JWT_SECRET}
      DB_AFTER_CONNECT_QUERY: SET search_path TO _realtime
      DB_ENC_KEY: supabaserealtime
      DB_HOST: ${POSTGRES_HOST:-db}
      DB_NAME: ${POSTGRES_DB:-postgres}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_PORT: ${POSTGRES_PORT:-5432}
      DB_USER: supabase_admin
      DNS_NODES: ''''''
      ENABLE_TAILSCALE: 'false'
      ERL_AFLAGS: -proto_dist inet_tcp
      FLY_ALLOC_ID: fly123
      FLY_APP_NAME: realtime
      PORT: 4000
      SECRET_KEY_BASE: ${REALTIME_SECRET_KEY_BASE:-UpNVntn3cDxHJpq99YMc1T1AQgQpc8kfYTuRgBiYa15BLrx8etQoXz3gZv1/u2oq}
    image: supabase/realtime:v2.27.5
    networks:
    - supabase-network
  rest:
    command: postgrest
    container_name: supabase-rest
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGRST_APP_SETTINGS_JWT_EXP: ${JWT_EXPIRY:-3600}
      PGRST_APP_SETTINGS_JWT_SECRET: ${JWT_SECRET}
      PGRST_DB_ANON_ROLE: anon
      PGRST_DB_SCHEMAS: ${PGRST_DB_SCHEMAS:-public,storage,graphql_public}
      PGRST_DB_URI: postgres://authenticator:${POSTGRES_PASSWORD}@${POSTGRES_HOST:-db}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-postgres}
      PGRST_DB_USE_LEGACY_GUCS: 'false'
      PGRST_JWT_SECRET: ${JWT_SECRET}
    image: postgrest/postgrest:v12.0.2
    networks:
    - supabase-network
  storage:
    container_name: supabase-storage
    depends_on:
      db:
        condition: service_healthy
      imgproxy:
        condition: service_started
      rest:
        condition: service_started
    environment:
      ANON_KEY: ${ANON_KEY}
      DATABASE_URL: postgres://supabase_storage_admin:${POSTGRES_PASSWORD}@${POSTGRES_HOST:-db}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-postgres}
      ENABLE_IMAGE_TRANSFORMATION: 'true'
      FILE_SIZE_LIMIT: 52428800
      FILE_STORAGE_BACKEND_PATH: /var/lib/storage
      GLOBAL_S3_BUCKET: stub
      IMGPROXY_URL: http://imgproxy:8080
      PGRST_JWT_SECRET: ${JWT_SECRET}
      POSTGREST_URL: http://rest:3000
      REGION: stub
      SERVICE_KEY: ${SERVICE_ROLE_KEY}
      STORAGE_BACKEND: file
      TENANT_ID: stub
    image: supabase/storage-api:v0.46.4
    networks:
    - supabase-network
    volumes:
    - ${STORAGE_DATA_PATH}:/var/lib/storage:z
  studio:
    container_name: supabase-studio
    depends_on:
      db:
        condition: service_healthy
      meta:
        condition: service_started
    environment:
      DEFAULT_ORGANIZATION_NAME: ${STUDIO_DEFAULT_ORGANIZATION:-Default Organization}
      DEFAULT_PROJECT_NAME: ${STUDIO_DEFAULT_PROJECT:-Default Project}
      LOGFLARE_API_KEY: ${LOGFLARE_API_KEY:-}
      LOGFLARE_URL: http://analytics:4000
      NEXT_ANALYTICS_BACKEND_PROVIDER: postgres
      NEXT_PUBLIC_ENABLE_LOGS: true
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      STUDIO_PG_META_URL: http://meta:8080
      SUPABASE_ANON_KEY: ${ANON_KEY}
      SUPABASE_PUBLIC_URL: ${SUPABASE_PUBLIC_URL}
      SUPABASE_SERVICE_KEY: ${SERVICE_ROLE_KEY}
      SUPABASE_URL: http://kong:8000
    expose:
    - '3000'
    image: supabase/studio:20240101-8e4a094
    networks:
    - supabase-network
